"""add_review_and_collaboration_tables

Revision ID: aed5adc7c93b
Revises: 0ee98bee8401
Create Date: 2026-07-19 09:36:14.825380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "aed5adc7c93b"
down_revision: Union[str, Sequence[str], None] = "0ee98bee8401"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_activity_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("user", sa.String(length=100), nullable=False),
        sa.Column("details", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_review_activity_logs_request_id_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_activity_logs")),
    )
    op.create_table(
        "review_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("reviewer", sa.String(length=100), nullable=False),
        sa.Column("assigned_by", sa.String(length=100), nullable=False),
        sa.Column("assigned_at", sa.String(length=100), nullable=False),
        sa.Column("unassigned_at", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_review_assignments_request_id_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_assignments")),
    )
    op.create_table(
        "review_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("creator", sa.String(length=100), nullable=False),
        sa.Column("request_status", sa.String(length=50), nullable=False),
        sa.Column("config_hash", sa.String(length=100), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_review_snapshots_request_id_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_snapshots")),
    )
    op.create_table(
        "claim_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("user", sa.String(length=100), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_claim_comments_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["claim_comments.id"],
            name=op.f("fk_claim_comments_parent_id_claim_comments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_comments")),
    )
    op.create_table(
        "pinned_evidences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.String(length=100), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("pinned_by", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name=op.f("fk_pinned_evidences_claim_id_claims"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_pinned_evidences_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pinned_evidences")),
    )
    op.create_table(
        "comment_mentions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("user", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["claim_comments.id"],
            name=op.f("fk_comment_mentions_comment_id_claim_comments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_mentions")),
    )
    op.add_column("claims", sa.Column("review_notes", sa.String(), nullable=True))
    op.add_column(
        "claims", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column(
        "requests", sa.Column("assigned_reviewer", sa.String(length=100), nullable=True)
    )
    op.add_column("requests", sa.Column("review_notes", sa.String(), nullable=True))
    op.add_column(
        "requests",
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "version")
    op.drop_column("requests", "review_notes")
    op.drop_column("requests", "assigned_reviewer")
    op.drop_column("claims", "version")
    op.drop_column("claims", "review_notes")
    op.drop_table("comment_mentions")
    op.drop_table("pinned_evidences")
    op.drop_table("claim_comments")
    op.drop_table("review_snapshots")
    op.drop_table("review_assignments")
    op.drop_table("review_activity_logs")
    # ### end Alembic commands ###
