"""add_v1_1_auth_tables

Revision ID: bccc9a1c6b5c
Revises: c6b2f053f720
Create Date: 2026-07-21 13:48:24.760718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bccc9a1c6b5c"
down_revision: Union[str, Sequence[str], None] = "c6b2f053f720"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "Owner",
                "Admin",
                "Lead Reviewer",
                "Reviewer",
                "Auditor",
                name="userrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                "suspended",
                "pending_verification",
                name="userstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=True),
        sa.Column("provider_picture", sa.String(length=500), nullable=True),
        sa.Column("provider_username", sa.String(length=255), nullable=True),
        sa.Column("provider_metadata", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_accounts")),
        sa.UniqueConstraint(
            "provider", "provider_user_id", name="uq_oauth_provider_user_id"
        ),
    )
    op.create_index(
        op.f("ix_oauth_accounts_provider"), "oauth_accounts", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_accounts_user_id"), "oauth_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_family", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_token", sa.String(length=64), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_ip", sa.String(length=45), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expires_at > created_at",
            name=op.f("ck_refresh_tokens_ck_refresh_tokens_expires_after_created"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"),
        "refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_family"),
        "refresh_tokens",
        ["token_family"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("browser", sa.String(length=50), nullable=True),
        sa.Column("operating_system", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expires_at > created_at",
            name=op.f("ck_sessions_ck_sessions_expires_after_created"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(
        op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_session_token_hash"),
        "sessions",
        ["session_token_hash"],
        unique=True,
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.add_column(
        "audit_log", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "audit_log", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "claim_comments", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "claim_comments", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "claims", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "claims", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "comment_mentions", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "comment_mentions", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "document_chunks", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "document_chunks", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "pinned_evidences", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "pinned_evidences", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_activity_logs",
        sa.Column("created_by", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "report_activity_logs",
        sa.Column("updated_by", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "report_citations", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_citations", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_findings", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_findings", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_sections", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_sections", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_templates", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "report_templates", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "reports", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "requests", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "requests", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "review_activity_logs",
        sa.Column("created_by", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "review_activity_logs",
        sa.Column("updated_by", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "review_assignments",
        sa.Column("created_by", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "review_assignments",
        sa.Column("updated_by", sa.String(length=36), nullable=True),
    )
    op.add_column(
        "review_snapshots", sa.Column("created_by", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "review_snapshots", sa.Column("updated_by", sa.String(length=36), nullable=True)
    )
    op.add_column("runs", sa.Column("created_by", sa.String(length=36), nullable=True))
    op.add_column("runs", sa.Column("updated_by", sa.String(length=36), nullable=True))
    op.add_column("tasks", sa.Column("created_by", sa.String(length=36), nullable=True))
    op.add_column("tasks", sa.Column("updated_by", sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "updated_by")
    op.drop_column("tasks", "created_by")
    op.drop_column("runs", "updated_by")
    op.drop_column("runs", "created_by")
    op.drop_column("review_snapshots", "updated_by")
    op.drop_column("review_snapshots", "created_by")
    op.drop_column("review_assignments", "updated_by")
    op.drop_column("review_assignments", "created_by")
    op.drop_column("review_activity_logs", "updated_by")
    op.drop_column("review_activity_logs", "created_by")
    op.drop_column("requests", "updated_by")
    op.drop_column("requests", "created_by")
    op.drop_column("reports", "updated_by")
    op.drop_column("report_templates", "updated_by")
    op.drop_column("report_templates", "created_by")
    op.drop_column("report_sections", "updated_by")
    op.drop_column("report_sections", "created_by")
    op.drop_column("report_findings", "updated_by")
    op.drop_column("report_findings", "created_by")
    op.drop_column("report_citations", "updated_by")
    op.drop_column("report_citations", "created_by")
    op.drop_column("report_activity_logs", "updated_by")
    op.drop_column("report_activity_logs", "created_by")
    op.drop_column("pinned_evidences", "updated_by")
    op.drop_column("pinned_evidences", "created_by")
    op.drop_column("documents", "updated_by")
    op.drop_column("documents", "created_by")
    op.drop_column("document_chunks", "updated_by")
    op.drop_column("document_chunks", "created_by")
    op.drop_column("comment_mentions", "updated_by")
    op.drop_column("comment_mentions", "created_by")
    op.drop_column("claims", "updated_by")
    op.drop_column("claims", "created_by")
    op.drop_column("claim_comments", "updated_by")
    op.drop_column("claim_comments", "created_by")
    op.drop_column("audit_log", "updated_by")
    op.drop_column("audit_log", "created_by")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_session_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_family"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts")
    op.drop_index(op.f("ix_oauth_accounts_provider"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
